### ISSUE TITLE
shit code

### ISSUE THREAD

**Issue by AccessibleObject** [Bula-jpg/SimpleCore#2]
kys. you shouldn't make plugins when you don't know how to use basics of bukkit api.

90% skidded, 10% made with my help

discord RuntimeException#0001

**Comment by Bula-jpg** [comment]
Go cry

**Comment by allinkdev** [comment]
> kys. you shouldn't make plugins when you don't know how to use basics of bukkit api.
> 
> 90% skidded, 10% made with my help
> 
> discord RuntimeException#0001

Ironic
